/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ymz_terminal_Terminal */

#ifndef _Included_com_ymz_terminal_Terminal
#define _Included_com_ymz_terminal_Terminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ymz_terminal_Terminal
 * Method:    createSubprocess
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[III)I
 */
JNIEXPORT jint JNICALL Java_com_ymz_terminal_Jni_createSubprocess
  (JNIEnv *, jclass, jstring, jstring, jobjectArray, jobjectArray, jintArray);

/*
 * Class:     com_ymz_terminal_Terminal
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ymz_terminal_Jni_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ymz_terminal_Terminal
 * Method:    waitFor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ymz_terminal_Jni_waitFor
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
